# These are supported funding model platforms
Support the project development & potential costs with Litecoin!
Those who contribute to this project will receieve bonus UBI Credits.

Litecoin: LN9WM17hmRNCELXswCvDFVGQwccKP1AmYM

Thank You,
-Anon86
